name: Track2
suffix: ~  # add suffix to saved images
model: srgan
distortion: sr
scale: 2
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]

datasets:
  test_1:  # the 1st test dataset
    name: DPED
    mode: LR
    dataroot_LR: ./image_test

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4

#### path
path:
  pretrain_model_G: ./RealSR/pretrained_model/DPED.pth
  results_root: ./results/

back_projection: False
back_projection_lamda: !!float 0.2